-- ============================================================================
-- UNIFIED RASVIA SCHEMA — from scratch
-- Paste this into the Supabase SQL Editor to recreate all public tables.
-- Does NOT touch auth.* or storage.* (Supabase manages those).
-- ============================================================================

-- ── Enum types ──────────────────────────────────────────────────────────────
-- (We intentionally do NOT create order_status enum — orders.status uses TEXT + CHECK)

CREATE TYPE public.waitlist_status AS ENUM (
    'waiting', 'notified', 'seated', 'cancelled', 'no_show'
);

-- ── Functions ───────────────────────────────────────────────────────────────

-- Auto-create a profile row when a new auth user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    INSERT INTO public.profiles (id) VALUES (NEW.id) ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;

-- Check if a restaurant is currently open based on its hours
CREATE OR REPLACE FUNCTION public.is_open(restaurant_id_input bigint) RETURNS boolean
    LANGUAGE plpgsql STABLE AS $$
DECLARE is_open_now boolean;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM restaurant_hours
        WHERE restaurant_id = restaurant_id_input
          AND day_of_week = extract(dow FROM timezone('America/Chicago', now()))
          AND (timezone('America/Chicago', now()))::time BETWEEN open_time AND close_time
    ) INTO is_open_now;
    RETURN is_open_now;
END;
$$;

-- Auto-update updated_at on orders
CREATE OR REPLACE FUNCTION public.set_orders_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- Helper: get current user's restaurant_id (SECURITY DEFINER = bypasses RLS)
CREATE OR REPLACE FUNCTION public.get_my_restaurant_id()
RETURNS bigint
LANGUAGE sql STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT restaurant_id FROM restaurant_staff WHERE user_id = auth.uid() LIMIT 1;
$$;

-- Helper: is the current user an admin/owner at their restaurant?
CREATE OR REPLACE FUNCTION public.am_i_restaurant_admin()
RETURNS boolean
LANGUAGE sql STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1 FROM restaurant_staff
        WHERE user_id = auth.uid()
          AND (role = 'admin' OR role = 'owner')
    );
$$;

-- ── Tables (dependency order: parents first) ────────────────────────────────

-- 1. restaurants
CREATE TABLE public.restaurants (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    address     text,
    description text,
    image_url   text,
    current_wait_time integer DEFAULT 0,
    is_waitlist_open  boolean DEFAULT true,
    rating      numeric DEFAULT 0.0,
    price_range text DEFAULT '$$',
    cuisine_tags text[],
    lat         double precision,
    long        double precision,
    owner_id    uuid REFERENCES auth.users(id),
    created_at  timestamptz DEFAULT timezone('utc', now()),
    is_featured boolean DEFAULT false,
    is_enabled  boolean,
    waitlist_open boolean,
    stripe_account_id text
);
COMMENT ON TABLE  public.restaurants IS 'All restaurants on Rasvia. Each row is one restaurant location.';
COMMENT ON COLUMN public.restaurants.name IS 'Restaurant display name';
COMMENT ON COLUMN public.restaurants.current_wait_time IS 'Estimated wait in minutes. Set to 999 to show "Closed".';
COMMENT ON COLUMN public.restaurants.is_waitlist_open IS 'Legacy flag — use waitlist_open instead';
COMMENT ON COLUMN public.restaurants.waitlist_open IS 'Whether the restaurant is currently accepting waitlist entries';
COMMENT ON COLUMN public.restaurants.is_enabled IS 'Master on/off switch — if FALSE the restaurant is hidden from the app';
COMMENT ON COLUMN public.restaurants.stripe_account_id IS 'Connected Stripe account ID for card payments (acct_xxx)';
COMMENT ON COLUMN public.restaurants.cuisine_tags IS 'Array of cuisine labels shown on the restaurant card, e.g. {"Indian", "Biryani"}';

-- 2. profiles
CREATE TABLE public.profiles (
    id          uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    phone_number text,
    full_name   text,
    avatar_url  text,
    created_at  timestamptz DEFAULT timezone('utc', now()),
    location_city text DEFAULT 'Frisco, TX',
    dietary_type text,
    restricted_days text[] DEFAULT '{}',
    spice_level text DEFAULT 'Medium',
    onboarding_completed boolean DEFAULT false,
    updated_at  timestamptz DEFAULT now(),
    saved_address text,
    home_lat    numeric,
    home_long   numeric,
    role        text DEFAULT 'user',
    is_shadow_banned boolean DEFAULT false,
    favorite_restaurants text,
    CONSTRAINT profiles_dietary_type_check CHECK (dietary_type IN ('Vegetarian','Non-Veg','Vegan','Jain','Halal')),
    CONSTRAINT profiles_role_check CHECK (role IN ('user','admin','restaurant_owner')),
    CONSTRAINT profiles_spice_level_check CHECK (spice_level IN ('Mild','Medium','Spicy','Indian Spicy'))
);
COMMENT ON TABLE  public.profiles IS 'User profiles — one row per signed-up customer. Created automatically on sign-up.';
COMMENT ON COLUMN public.profiles.dietary_type IS 'Customer dietary preference: Vegetarian, Non-Veg, Vegan, Jain, or Halal';
COMMENT ON COLUMN public.profiles.role IS 'user = regular customer, admin = platform admin, restaurant_owner = owner';
COMMENT ON COLUMN public.profiles.is_shadow_banned IS 'If TRUE the user can still use the app but their waitlist entries and orders are hidden from restaurants';
COMMENT ON COLUMN public.profiles.favorite_restaurants IS 'JSON-encoded array of restaurant IDs the user has favorited';
COMMENT ON COLUMN public.profiles.saved_address IS 'Customer saved home/work address text';

-- 3. menu_categories
CREATE TABLE public.menu_categories (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id bigint REFERENCES public.restaurants(id) ON DELETE CASCADE,
    name        text NOT NULL,
    sort_order  integer DEFAULT 0
);
COMMENT ON TABLE public.menu_categories IS 'Optional structured categories for menu items (linked by category_id).';

-- 4. menu_items
CREATE TABLE public.menu_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id bigint REFERENCES public.restaurants(id) ON DELETE CASCADE,
    category_id bigint REFERENCES public.menu_categories(id),
    name        text NOT NULL,
    description text,
    price       numeric NOT NULL,
    image_url   text,
    is_available boolean DEFAULT true,
    is_vegetarian boolean DEFAULT false,
    is_spicy    boolean DEFAULT false,
    category    text,
    meal_times  text[] DEFAULT '{}',
    in_stock    boolean DEFAULT true NOT NULL
);
COMMENT ON TABLE  public.menu_items IS 'Menu items for each restaurant. Each row is one dish.';
COMMENT ON COLUMN public.menu_items.is_available IS 'Legacy availability flag — use in_stock instead';
COMMENT ON COLUMN public.menu_items.in_stock IS 'Whether this item can currently be ordered (toggled by staff)';
COMMENT ON COLUMN public.menu_items.meal_times IS 'Which meals this item appears in, e.g. {"breakfast","lunch","dinner"}';
COMMENT ON COLUMN public.menu_items.category IS 'Text category name for grouping (e.g. "Starters", "Mains", "Drinks")';

-- 5. orders (unified: uses 'pending' not 'active')
CREATE TABLE public.orders (
    id          bigint NOT NULL,
    restaurant_id bigint NOT NULL REFERENCES public.restaurants(id),
    table_number text,
    party_size  integer DEFAULT 1,
    order_type  text DEFAULT 'dine_in',
    status      text DEFAULT 'pending',
    meal_period text DEFAULT 'dinner',
    subtotal    numeric(10,2) DEFAULT 0,
    tip_amount  numeric(10,2) DEFAULT 0,
    tip_percent numeric(5,2),
    payment_method text DEFAULT 'cash',
    notes       text,
    waitlist_entry_id text,
    party_session_id  text,
    customer_name     text,
    created_at  timestamptz DEFAULT now(),
    closed_at   timestamptz,
    created_by  text,
    stripe_session_id text,
    customer_phone    text,
    updated_at  timestamptz DEFAULT now(),
    CONSTRAINT orders_meal_period_check CHECK (meal_period IN ('breakfast','lunch','dinner','special')),
    CONSTRAINT orders_order_type_check  CHECK (order_type IN ('dine_in','pre_order','takeout')),
    CONSTRAINT orders_status_check      CHECK (status IN ('pending','pending_payment','preparing','ready','served','completed','cancelled'))
);

CREATE SEQUENCE public.orders_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.orders_id_seq OWNED BY public.orders.id;
ALTER TABLE ONLY public.orders ALTER COLUMN id SET DEFAULT nextval('public.orders_id_seq');
ALTER TABLE ONLY public.orders ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

CREATE TRIGGER trg_orders_updated_at BEFORE UPDATE ON public.orders
    FOR EACH ROW EXECUTE FUNCTION public.set_orders_updated_at();

COMMENT ON TABLE  public.orders IS 'All customer orders — dine-in, takeout, and pre-orders.';
COMMENT ON COLUMN public.orders.status IS 'Order lifecycle: pending → preparing → ready → served → completed. Can also be cancelled or pending_payment.';
COMMENT ON COLUMN public.orders.order_type IS 'How the order was placed: dine_in (at the table), pre_order (ordered before being seated), takeout (pickup)';
COMMENT ON COLUMN public.orders.meal_period IS 'Which meal: breakfast, lunch, dinner, or special';
COMMENT ON COLUMN public.orders.subtotal IS 'Sum of all item prices × quantities (before tax/tip)';
COMMENT ON COLUMN public.orders.tip_amount IS 'Dollar amount of tip left by the customer';
COMMENT ON COLUMN public.orders.tip_percent IS 'Tip as a percentage of subtotal';
COMMENT ON COLUMN public.orders.payment_method IS 'How the customer paid: cash or card';
COMMENT ON COLUMN public.orders.notes IS 'Special instructions or internal metadata (JSON).';
COMMENT ON COLUMN public.orders.customer_name IS 'Name provided by the customer at checkout';
COMMENT ON COLUMN public.orders.customer_phone IS 'Phone number for takeout/pre-order pickup notifications';
COMMENT ON COLUMN public.orders.waitlist_entry_id IS 'Links this order to a waitlist entry (for pre-orders placed while waiting)';
COMMENT ON COLUMN public.orders.party_session_id IS 'Links this order to a group ordering session';
COMMENT ON COLUMN public.orders.stripe_session_id IS 'Stripe Checkout session ID for card payments';
COMMENT ON COLUMN public.orders.created_by IS 'User ID of whoever placed the order (from auth.users)';
COMMENT ON COLUMN public.orders.table_number IS 'Table number assigned by the restaurant (text, e.g. "12" or "Patio 3")';
COMMENT ON COLUMN public.orders.updated_at IS 'Automatically set whenever the order is modified';

-- 6. order_items
CREATE TABLE public.order_items (
    id          bigint NOT NULL,
    order_id    bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    menu_item_id bigint REFERENCES public.menu_items(id),
    name        text NOT NULL,
    price       numeric(10,2) NOT NULL,
    quantity    integer DEFAULT 1,
    is_vegetarian boolean DEFAULT false,
    notes       text,
    created_at  timestamptz DEFAULT now(),
    meal_period text
);

CREATE SEQUENCE public.order_items_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.order_items_id_seq OWNED BY public.order_items.id;
ALTER TABLE ONLY public.order_items ALTER COLUMN id SET DEFAULT nextval('public.order_items_id_seq');
ALTER TABLE ONLY public.order_items ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);

COMMENT ON TABLE  public.order_items IS 'Individual line items within an order.';
COMMENT ON COLUMN public.order_items.name IS 'Display name of the menu item (copied at order time so it survives menu changes)';
COMMENT ON COLUMN public.order_items.price IS 'Unit price at time of order';
COMMENT ON COLUMN public.order_items.is_vegetarian IS 'Whether this item is vegetarian/vegan';
COMMENT ON COLUMN public.order_items.meal_period IS 'Optional: which meal period this item belongs to';

-- 7. party_sessions
CREATE TABLE public.party_sessions (
    id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    restaurant_id bigint NOT NULL REFERENCES public.restaurants(id),
    host_user_id uuid NOT NULL REFERENCES auth.users(id),
    status      text DEFAULT 'open',
    created_at  timestamptz DEFAULT now(),
    submitted_at text
);
COMMENT ON TABLE  public.party_sessions IS 'Group ordering sessions — one host creates a session, guests join via link.';
COMMENT ON COLUMN public.party_sessions.status IS 'open (guests can add items), submitted (order placed), cancelled';
COMMENT ON COLUMN public.party_sessions.submitted_at IS 'When the host submitted the group order';

-- 8. party_items
CREATE TABLE public.party_items (
    id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id  uuid NOT NULL REFERENCES public.party_sessions(id),
    menu_item_id bigint NOT NULL REFERENCES public.menu_items(id),
    added_by_name text NOT NULL,
    guest_uuid  uuid DEFAULT gen_random_uuid(),
    quantity    integer DEFAULT 1,
    special_requests text,
    created_at  timestamptz DEFAULT now()
);
COMMENT ON TABLE  public.party_items IS 'Individual items added by guests within a group ordering session.';
COMMENT ON COLUMN public.party_items.added_by_name IS 'Display name of the guest who added this item';
COMMENT ON COLUMN public.party_items.special_requests IS 'Dietary or preparation notes for this item';

-- 9. group_orders (NEW — was missing from the old schema)
CREATE TABLE public.group_orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_session_id uuid NOT NULL REFERENCES public.party_sessions(id) ON DELETE CASCADE,
    restaurant_id bigint NOT NULL REFERENCES public.restaurants(id),
    items       jsonb NOT NULL DEFAULT '[]'::jsonb,
    total       numeric(10,2) NOT NULL DEFAULT 0,
    submitted_at timestamptz DEFAULT now(),
    created_at  timestamptz DEFAULT now()
);
CREATE INDEX idx_group_orders_party_session ON public.group_orders (party_session_id);
CREATE INDEX idx_group_orders_restaurant ON public.group_orders (restaurant_id);
COMMENT ON TABLE  public.group_orders IS 'Submitted group orders — created when a party session host checks out.';
COMMENT ON COLUMN public.group_orders.items IS 'JSON array of items with name, price, quantity, and who added each';
COMMENT ON COLUMN public.group_orders.total IS 'Total dollar amount for the group order';

-- 10. waitlist_entries
CREATE TABLE public.waitlist_entries (
    id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id     uuid REFERENCES auth.users(id),
    restaurant_id bigint REFERENCES public.restaurants(id),
    party_size  integer DEFAULT 2 NOT NULL,
    status      public.waitlist_status DEFAULT 'waiting',
    phone_number text,
    name        text,
    created_at  timestamptz DEFAULT timezone('utc', now()),
    notified_at timestamptz,
    party_leader_name text
);
COMMENT ON TABLE  public.waitlist_entries IS 'Walk-in waitlist. One row per party waiting to be seated.';
COMMENT ON COLUMN public.waitlist_entries.status IS 'waiting → notified → seated (happy path) or cancelled / no_show';
COMMENT ON COLUMN public.waitlist_entries.party_leader_name IS 'The name of who checked in (party leader)';
COMMENT ON COLUMN public.waitlist_entries.party_size IS 'Number of guests in the party';
COMMENT ON COLUMN public.waitlist_entries.phone_number IS 'Contact phone number for notification';

-- 11. restaurant_hours
CREATE TABLE public.restaurant_hours (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id bigint NOT NULL REFERENCES public.restaurants(id),
    day_of_week integer NOT NULL,
    open_time   time NOT NULL,
    close_time  time NOT NULL
);
COMMENT ON TABLE  public.restaurant_hours IS 'Operating hours for each restaurant. One row per day-of-week per restaurant.';
COMMENT ON COLUMN public.restaurant_hours.day_of_week IS '0 = Sunday, 1 = Monday, ... 6 = Saturday';

-- 12. restaurant_roles
CREATE TABLE public.restaurant_roles (
    id          bigint NOT NULL,
    restaurant_id bigint NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
    name        text NOT NULL,
    is_owner    boolean DEFAULT false NOT NULL,
    created_at  timestamptz DEFAULT now() NOT NULL
);
CREATE SEQUENCE public.restaurant_roles_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.restaurant_roles_id_seq OWNED BY public.restaurant_roles.id;
ALTER TABLE ONLY public.restaurant_roles ALTER COLUMN id SET DEFAULT nextval('public.restaurant_roles_id_seq');
ALTER TABLE ONLY public.restaurant_roles ADD CONSTRAINT restaurant_roles_pkey PRIMARY KEY (id);
COMMENT ON TABLE  public.restaurant_roles IS 'Custom roles defined per restaurant (e.g. Manager, Host, Server).';
COMMENT ON COLUMN public.restaurant_roles.is_owner IS 'If TRUE this role has full access to everything — cannot be restricted';

-- 13. restaurant_staff
CREATE TABLE public.restaurant_staff (
    id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id     uuid NOT NULL REFERENCES auth.users(id),
    restaurant_id bigint NOT NULL REFERENCES public.restaurants(id),
    role        text DEFAULT 'manager',
    role_id     bigint REFERENCES public.restaurant_roles(id) ON DELETE SET NULL
);
COMMENT ON TABLE  public.restaurant_staff IS 'Maps users to restaurants they work at. To give someone dashboard access, add a row here.';
COMMENT ON COLUMN public.restaurant_staff.role IS 'Set to admin or owner for full access. Other values (staff, manager) have limited access based on role_id permissions.';
COMMENT ON COLUMN public.restaurant_staff.role_id IS 'FK to restaurant_roles for granular RBAC permissions (optional if role = admin)';

-- 14. role_permissions
CREATE TABLE public.role_permissions (
    id          bigint NOT NULL,
    role_id     bigint NOT NULL REFERENCES public.restaurant_roles(id) ON DELETE CASCADE,
    permission  text NOT NULL
);
CREATE SEQUENCE public.role_permissions_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.role_permissions_id_seq OWNED BY public.role_permissions.id;
ALTER TABLE ONLY public.role_permissions ALTER COLUMN id SET DEFAULT nextval('public.role_permissions_id_seq');
ALTER TABLE ONLY public.role_permissions ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);
COMMENT ON TABLE  public.role_permissions IS 'Individual permissions granted to each restaurant role.';
COMMENT ON COLUMN public.role_permissions.permission IS 'Permission key like view_orders, manage_menu, manage_team, etc.';

-- 15. system_config
CREATE TABLE public.system_config (
    key   text PRIMARY KEY,
    value text DEFAULT '' NOT NULL
);
COMMENT ON TABLE public.system_config IS 'Global key/value config. Used for feature flags and platform settings.';

-- ── Trigger: auto-create profile on sign-up ─────────────────────────────────
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── Row Level Security ──────────────────────────────────────────────────────

-- profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert own profile"  ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can read own profile"    ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Users can update own profile"  ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);
CREATE POLICY "Users manage own profile"      ON public.profiles USING (auth.uid() = id);
CREATE POLICY "users_cannot_change_own_role"  ON public.profiles FOR UPDATE
    USING ((id = auth.uid()) OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'))
    WITH CHECK ((role = (SELECT p.role FROM profiles p WHERE p.id = auth.uid())) OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

-- restaurants
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to restaurants" ON public.restaurants FOR SELECT USING (true);
CREATE POLICY "Public Read Restaurants"        ON public.restaurants FOR SELECT USING (true);
CREATE POLICY "owner_read_own_restaurant"      ON public.restaurants FOR SELECT USING (true);
CREATE POLICY "Staff can see own restaurant"   ON public.restaurants FOR SELECT USING (id IN (SELECT restaurant_id FROM restaurant_staff WHERE user_id = auth.uid()));
CREATE POLICY "Staff can update own restaurant" ON public.restaurants FOR UPDATE USING (id IN (SELECT restaurant_id FROM restaurant_staff WHERE user_id = auth.uid()));
CREATE POLICY "Admins can insert restaurants"  ON public.restaurants FOR INSERT WITH CHECK (auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin'));
CREATE POLICY "Admins can update restaurants"  ON public.restaurants FOR UPDATE USING (auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin'));
CREATE POLICY "Admins can delete restaurants"  ON public.restaurants FOR DELETE USING (auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin'));
CREATE POLICY "only_admins_delete_restaurants" ON public.restaurants FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "only_admins_insert_restaurants" ON public.restaurants FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

-- menu_items
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Menu"                   ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Allow public read access to menu_items" ON public.menu_items FOR SELECT USING (true);

-- menu_categories
ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;

-- orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_insert_orders" ON public.orders FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "auth_select_orders" ON public.orders FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_update_orders" ON public.orders FOR UPDATE USING (auth.role() = 'authenticated');

-- order_items
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_insert_order_items" ON public.order_items FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "auth_select_order_items" ON public.order_items FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_update_order_items" ON public.order_items FOR UPDATE USING (auth.role() = 'authenticated');

-- party_sessions
ALTER TABLE public.party_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Session Access" ON public.party_sessions FOR SELECT USING (true);

-- party_items
ALTER TABLE public.party_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Item Access"    ON public.party_items FOR SELECT USING (true);
CREATE POLICY "Guests Can Add Items"  ON public.party_items FOR INSERT WITH CHECK (true);

-- group_orders
ALTER TABLE public.group_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated read/write on group_orders" ON public.group_orders FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow service_role full access on group_orders" ON public.group_orders FOR ALL TO service_role USING (true) WITH CHECK (true);

-- waitlist_entries
ALTER TABLE public.waitlist_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users join waitlist"     ON public.waitlist_entries FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users see own waitlist"  ON public.waitlist_entries FOR SELECT USING (auth.uid() = user_id);

-- restaurant_hours
ALTER TABLE public.restaurant_hours ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access"                    ON public.restaurant_hours FOR SELECT USING (true);
CREATE POLICY "Staff can read their restaurant hours"  ON public.restaurant_hours FOR SELECT USING (restaurant_id IN (SELECT restaurant_id FROM restaurant_staff WHERE user_id = auth.uid()));
CREATE POLICY "Staff can insert their restaurant hours" ON public.restaurant_hours FOR INSERT WITH CHECK (restaurant_id IN (SELECT restaurant_id FROM restaurant_staff WHERE user_id = auth.uid()));
CREATE POLICY "Staff can delete their restaurant hours" ON public.restaurant_hours FOR DELETE USING (restaurant_id IN (SELECT restaurant_id FROM restaurant_staff WHERE user_id = auth.uid()));

-- restaurant_roles (uses SECURITY DEFINER helpers — no self-referencing)
ALTER TABLE public.restaurant_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff can view own restaurant roles" ON public.restaurant_roles FOR SELECT
    USING (restaurant_id = get_my_restaurant_id());
CREATE POLICY "Owners can manage roles" ON public.restaurant_roles FOR ALL
    USING (restaurant_id = get_my_restaurant_id() AND am_i_restaurant_admin())
    WITH CHECK (restaurant_id = get_my_restaurant_id() AND am_i_restaurant_admin());

-- role_permissions
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff can view role permissions" ON public.role_permissions FOR SELECT
    USING (role_id IN (SELECT id FROM restaurant_roles WHERE restaurant_id = get_my_restaurant_id()));
CREATE POLICY "Owners can manage role permissions" ON public.role_permissions FOR ALL
    USING (am_i_restaurant_admin() AND role_id IN (SELECT id FROM restaurant_roles WHERE restaurant_id = get_my_restaurant_id()))
    WITH CHECK (am_i_restaurant_admin() AND role_id IN (SELECT id FROM restaurant_roles WHERE restaurant_id = get_my_restaurant_id()));

-- restaurant_staff
ALTER TABLE public.restaurant_staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff can view restaurant team" ON public.restaurant_staff FOR SELECT
    USING (restaurant_id = get_my_restaurant_id());
CREATE POLICY "Owners can manage staff" ON public.restaurant_staff FOR ALL
    USING (restaurant_id = get_my_restaurant_id() AND am_i_restaurant_admin())
    WITH CHECK (restaurant_id = get_my_restaurant_id() AND am_i_restaurant_admin());

-- system_config (no RLS — admin only via service_role)

