-- ============================================================================
-- MIGRATION: Unify Supabase schema for Rasvia1 (app) + RasviaWeb (dashboard)
-- Date: 2026-03-05
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- 1. Drop dead tables first (cart_sessions depends on order_status enum)
-- ────────────────────────────────────────────────────────────────────────────
DROP TABLE IF EXISTS public.cart_items;
DROP TABLE IF EXISTS public.cart_sessions;

-- ────────────────────────────────────────────────────────────────────────────
-- 2. Now drop the unused enum type (orders.status uses TEXT + CHECK, not this)
-- ────────────────────────────────────────────────────────────────────────────
DROP TYPE IF EXISTS public.order_status;

-- ────────────────────────────────────────────────────────────────────────────
-- 3. Create missing group_orders table
--    (Referenced by payment-redirect edge function and join/[id].tsx)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.group_orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_session_id uuid NOT NULL REFERENCES public.party_sessions(id) ON DELETE CASCADE,
    restaurant_id    bigint NOT NULL REFERENCES public.restaurants(id),
    items       jsonb NOT NULL DEFAULT '[]'::jsonb,
    total       numeric(10,2) NOT NULL DEFAULT 0,
    submitted_at timestamptz DEFAULT now(),
    created_at   timestamptz DEFAULT now()
);

ALTER TABLE public.group_orders OWNER TO postgres;

-- Index for fast lookups by party session
CREATE INDEX IF NOT EXISTS idx_group_orders_party_session
    ON public.group_orders (party_session_id);

CREATE INDEX IF NOT EXISTS idx_group_orders_restaurant
    ON public.group_orders (restaurant_id);

-- ────────────────────────────────────────────────────────────────────────────
-- 4. Migrate order status: 'active' → 'pending'
--    Then update the CHECK constraint to use the unified set.
-- ────────────────────────────────────────────────────────────────────────────
UPDATE public.orders SET status = 'pending' WHERE status = 'active';

ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE public.orders ADD CONSTRAINT orders_status_check
    CHECK (status IN (
        'pending',           -- Order placed, waiting to be worked on
        'pending_payment',   -- Stripe checkout started but not yet paid
        'preparing',         -- Kitchen is making it
        'ready',             -- Ready for pickup / serving
        'served',            -- Delivered to the table
        'completed',         -- Fully done, closed out
        'cancelled'          -- Cancelled by customer or staff
    ));

-- ────────────────────────────────────────────────────────────────────────────
-- 5. Add customer_phone column to orders
--    (Previously stored as JSON inside the notes column by RasviaWeb)
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_phone text;

COMMENT ON COLUMN public.orders.customer_phone
    IS 'Phone number for takeout/pre-order pickup notifications';

-- ────────────────────────────────────────────────────────────────────────────
-- 6. Add updated_at column to orders
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- Auto-update updated_at on every row change
CREATE OR REPLACE FUNCTION public.set_orders_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_orders_updated_at ON public.orders;
CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION public.set_orders_updated_at();

-- ────────────────────────────────────────────────────────────────────────────
-- 7. Human-readable COMMENTs for customer-service staff
--    (These show up as tooltips in the Supabase dashboard)
-- ────────────────────────────────────────────────────────────────────────────

-- restaurants
COMMENT ON TABLE  public.restaurants IS
    'All restaurants on Rasvia. Each row is one restaurant location.';
COMMENT ON COLUMN public.restaurants.name IS
    'Restaurant display name';
COMMENT ON COLUMN public.restaurants.current_wait_time IS
    'Estimated wait in minutes. Set to 999 to show "Closed".';
COMMENT ON COLUMN public.restaurants.is_waitlist_open IS
    'Legacy flag — use waitlist_open instead';
COMMENT ON COLUMN public.restaurants.waitlist_open IS
    'Whether the restaurant is currently accepting waitlist entries';
COMMENT ON COLUMN public.restaurants.is_enabled IS
    'Master on/off switch — if FALSE the restaurant is hidden from the app';
COMMENT ON COLUMN public.restaurants.stripe_account_id IS
    'Connected Stripe account ID for card payments (acct_xxx)';
COMMENT ON COLUMN public.restaurants.cuisine_tags IS
    'Array of cuisine labels shown on the restaurant card, e.g. {"Indian", "Biryani"}';

-- profiles
COMMENT ON TABLE  public.profiles IS
    'User profiles — one row per signed-up customer. Created automatically on sign-up.';
COMMENT ON COLUMN public.profiles.dietary_type IS
    'Customer dietary preference: Vegetarian, Non-Veg, Vegan, Jain, or Halal';
COMMENT ON COLUMN public.profiles.role IS
    'user = regular customer, admin = platform admin, restaurant_owner = owner';
COMMENT ON COLUMN public.profiles.is_shadow_banned IS
    'If TRUE the user can still use the app but their waitlist entries and orders are hidden from restaurants';
COMMENT ON COLUMN public.profiles.favorite_restaurants IS
    'JSON-encoded array of restaurant IDs the user has favorited';
COMMENT ON COLUMN public.profiles.saved_address IS
    'Customer saved home/work address text';

-- orders
COMMENT ON TABLE  public.orders IS
    'All customer orders — dine-in, takeout, and pre-orders.';
COMMENT ON COLUMN public.orders.status IS
    'Order lifecycle: pending → preparing → ready → served → completed. Can also be cancelled or pending_payment.';
COMMENT ON COLUMN public.orders.order_type IS
    'How the order was placed: dine_in (at the table), pre_order (ordered before being seated), takeout (pickup)';
COMMENT ON COLUMN public.orders.meal_period IS
    'Which meal: breakfast, lunch, dinner, or special';
COMMENT ON COLUMN public.orders.subtotal IS
    'Sum of all item prices × quantities (before tax/tip)';
COMMENT ON COLUMN public.orders.tip_amount IS
    'Dollar amount of tip left by the customer';
COMMENT ON COLUMN public.orders.tip_percent IS
    'Tip as a percentage of subtotal';
COMMENT ON COLUMN public.orders.payment_method IS
    'How the customer paid: cash or card';
COMMENT ON COLUMN public.orders.notes IS
    'Special instructions or internal metadata (JSON). For human-readable notes see the top-level text.';
COMMENT ON COLUMN public.orders.customer_name IS
    'Name provided by the customer at checkout';
COMMENT ON COLUMN public.orders.waitlist_entry_id IS
    'Links this order to a waitlist entry (for pre-orders placed while waiting)';
COMMENT ON COLUMN public.orders.party_session_id IS
    'Links this order to a group ordering session';
COMMENT ON COLUMN public.orders.stripe_session_id IS
    'Stripe Checkout session ID for card payments';
COMMENT ON COLUMN public.orders.created_by IS
    'User ID of whoever placed the order (from auth.users)';
COMMENT ON COLUMN public.orders.table_number IS
    'Table number assigned by the restaurant (text, e.g. "12" or "Patio 3")';
COMMENT ON COLUMN public.orders.updated_at IS
    'Automatically set whenever the order is modified';

-- order_items
COMMENT ON TABLE  public.order_items IS
    'Individual line items within an order.';
COMMENT ON COLUMN public.order_items.name IS
    'Display name of the menu item (copied at order time so it survives menu changes)';
COMMENT ON COLUMN public.order_items.price IS
    'Unit price at time of order';
COMMENT ON COLUMN public.order_items.is_vegetarian IS
    'Whether this item is vegetarian/vegan';
COMMENT ON COLUMN public.order_items.meal_period IS
    'Optional: which meal period this item belongs to';

-- waitlist_entries
COMMENT ON TABLE  public.waitlist_entries IS
    'Walk-in waitlist. One row per party waiting to be seated.';
COMMENT ON COLUMN public.waitlist_entries.status IS
    'waiting → notified → seated (happy path) or cancelled / no_show';
COMMENT ON COLUMN public.waitlist_entries.party_leader_name IS
    'The name of who checked in (party leader)';
COMMENT ON COLUMN public.waitlist_entries.party_size IS
    'Number of guests in the party';
COMMENT ON COLUMN public.waitlist_entries.phone_number IS
    'Contact phone number for notification';

-- menu_items
COMMENT ON TABLE  public.menu_items IS
    'Menu items for each restaurant. Each row is one dish.';
COMMENT ON COLUMN public.menu_items.is_available IS
    'Legacy availability flag — use in_stock instead';
COMMENT ON COLUMN public.menu_items.in_stock IS
    'Whether this item can currently be ordered (toggled by staff)';
COMMENT ON COLUMN public.menu_items.meal_times IS
    'Which meals this item appears in, e.g. {"breakfast","lunch","dinner"}';
COMMENT ON COLUMN public.menu_items.category IS
    'Text category name for grouping (e.g. "Starters", "Mains", "Drinks")';

-- menu_categories
COMMENT ON TABLE  public.menu_categories IS
    'Optional structured categories for menu items (linked by category_id).';

-- party_sessions
COMMENT ON TABLE  public.party_sessions IS
    'Group ordering sessions — one host creates a session, guests join via link.';
COMMENT ON COLUMN public.party_sessions.status IS
    'open (guests can add items), submitted (order placed), cancelled';
COMMENT ON COLUMN public.party_sessions.submitted_at IS
    'When the host submitted the group order';

-- party_items
COMMENT ON TABLE  public.party_items IS
    'Individual items added by guests within a group ordering session.';
COMMENT ON COLUMN public.party_items.added_by_name IS
    'Display name of the guest who added this item';
COMMENT ON COLUMN public.party_items.special_requests IS
    'Dietary or preparation notes for this item';

-- group_orders
COMMENT ON TABLE  public.group_orders IS
    'Submitted group orders — created when a party session host checks out.';
COMMENT ON COLUMN public.group_orders.items IS
    'JSON array of items with name, price, quantity, and who added each';
COMMENT ON COLUMN public.group_orders.total IS
    'Total dollar amount for the group order';

-- restaurant_hours
COMMENT ON TABLE  public.restaurant_hours IS
    'Operating hours for each restaurant. One row per day-of-week per restaurant.';
COMMENT ON COLUMN public.restaurant_hours.day_of_week IS
    '0 = Sunday, 1 = Monday, ... 6 = Saturday';

-- restaurant_staff
COMMENT ON TABLE  public.restaurant_staff IS
    'Maps users to restaurants they work at, with their role.';
COMMENT ON COLUMN public.restaurant_staff.role IS
    'Legacy text role (manager/admin). Use role_id for RBAC permissions.';
COMMENT ON COLUMN public.restaurant_staff.role_id IS
    'Foreign key to restaurant_roles for granular permissions';

-- restaurant_roles
COMMENT ON TABLE  public.restaurant_roles IS
    'Custom roles defined per restaurant (e.g. Manager, Host, Server).';
COMMENT ON COLUMN public.restaurant_roles.is_owner IS
    'If TRUE this role has full access to everything — cannot be restricted';

-- role_permissions
COMMENT ON TABLE  public.role_permissions IS
    'Individual permissions granted to each restaurant role.';
COMMENT ON COLUMN public.role_permissions.permission IS
    'Permission key like view_orders, manage_menu, manage_team, etc.';

-- system_config
COMMENT ON TABLE  public.system_config IS
    'Global key/value config. Used for feature flags and platform settings.';

-- ────────────────────────────────────────────────────────────────────────────
-- 8. RLS for group_orders
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.group_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read/write on group_orders"
    ON public.group_orders
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Also allow service_role (edge functions) full access
CREATE POLICY "Allow service_role full access on group_orders"
    ON public.group_orders
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);
